"""
ISO 3166-1 alpha-3 country codes.
Format: ('CODE', 'CODE - Country Name')
"""

COUNTRY_CHOICES = [
    ('AFG', 'AFG - Afganistán'),
    ('ALB', 'ALB - Albania'),
    ('DEU', 'DEU - Alemania'),
    ('AND', 'AND - Andorra'),
    ('AGO', 'AGO - Angola'),
    ('ATG', 'ATG - Antigua y Barbuda'),
    ('SAU', 'SAU - Arabia Saudita'),
    ('DZA', 'DZA - Argelia'),
    ('ARG', 'ARG - Argentina'),
    ('ARM', 'ARM - Armenia'),
    ('AUS', 'AUS - Australia'),
    ('AUT', 'AUT - Austria'),
    ('AZE', 'AZE - Azerbaiyán'),
    ('BHS', 'BHS - Bahamas'),
    ('BGD', 'BGD - Bangladés'),
    ('BRB', 'BRB - Barbados'),
    ('BHR', 'BHR - Baréin'),
    ('BEL', 'BEL - Bélgica'),
    ('BLZ', 'BLZ - Belice'),
    ('BEN', 'BEN - Benín'),
    ('BLR', 'BLR - Bielorrusia'),
    ('MMR', 'MMR - Birmania'),
    ('BOL', 'BOL - Bolivia'),
    ('BIH', 'BIH - Bosnia y Herzegovina'),
    ('BWA', 'BWA - Botsuana'),
    ('BRA', 'BRA - Brasil'),
    ('BRN', 'BRN - Brunéi'),
    ('BGR', 'BGR - Bulgaria'),
    ('BFA', 'BFA - Burkina Faso'),
    ('BDI', 'BDI - Burundi'),
    ('BTN', 'BTN - Bután'),
    ('CPV', 'CPV - Cabo Verde'),
    ('KHM', 'KHM - Camboya'),
    ('CMR', 'CMR - Camerún'),
    ('CAN', 'CAN - Canadá'),
    ('QAT', 'QAT - Catar'),
    ('TCD', 'TCD - Chad'),
    ('CHL', 'CHL - Chile'),
    ('CHN', 'CHN - China'),
    ('CYP', 'CYP - Chipre'),
    ('VAT', 'VAT - Ciudad del Vaticano'),
    ('COL', 'COL - Colombia'),
    ('COM', 'COM - Comoras'),
    ('PRK', 'PRK - Corea del Norte'),
    ('KOR', 'KOR - Corea del Sur'),
    ('CIV', 'CIV - Costa de Marfil'),
    ('CRI', 'CRI - Costa Rica'),
    ('HRV', 'HRV - Croacia'),
    ('CUB', 'CUB - Cuba'),
    ('DNK', 'DNK - Dinamarca'),
    ('DMA', 'DMA - Dominica'),
    ('ECU', 'ECU - Ecuador'),
    ('EGY', 'EGY - Egipto'),
    ('SLV', 'SLV - El Salvador'),
    ('ARE', 'ARE - Emiratos Árabes Unidos'),
    ('ERI', 'ERI - Eritrea'),
    ('SVK', 'SVK - Eslovaquia'),
    ('SVN', 'SVN - Eslovenia'),
    ('ESP', 'ESP - España'),
    ('USA', 'USA - Estados Unidos'),
    ('EST', 'EST - Estonia'),
    ('ETH', 'ETH - Etiopía'),
    ('PHL', 'PHL - Filipinas'),
    ('FIN', 'FIN - Finlandia'),
    ('FJI', 'FJI - Fiyi'),
    ('FRA', 'FRA - Francia'),
    ('GAB', 'GAB - Gabón'),
    ('GMB', 'GMB - Gambia'),
    ('GEO', 'GEO - Georgia'),
    ('GHA', 'GHA - Ghana'),
    ('GRD', 'GRD - Granada'),
    ('GRC', 'GRC - Grecia'),
    ('GTM', 'GTM - Guatemala'),
    ('GIN', 'GIN - Guinea'),
    ('GNQ', 'GNQ - Guinea Ecuatorial'),
    ('GNB', 'GNB - Guinea-Bisáu'),
    ('GUY', 'GUY - Guyana'),
    ('HTI', 'HTI - Haití'),
    ('HND', 'HND - Honduras'),
    ('HUN', 'HUN - Hungría'),
    ('IND', 'IND - India'),
    ('IDN', 'IDN - Indonesia'),
    ('IRQ', 'IRQ - Irak'),
    ('IRN', 'IRN - Irán'),
    ('IRL', 'IRL - Irlanda'),
    ('ISL', 'ISL - Islandia'),
    ('ISR', 'ISR - Israel'),
    ('ITA', 'ITA - Italia'),
    ('JAM', 'JAM - Jamaica'),
    ('JPN', 'JPN - Japón'),
    ('JOR', 'JOR - Jordania'),
    ('KAZ', 'KAZ - Kazajistán'),
    ('KEN', 'KEN - Kenia'),
    ('KGZ', 'KGZ - Kirguistán'),
    ('KIR', 'KIR - Kiribati'),
    ('KWT', 'KWT - Kuwait'),
    ('LAO', 'LAO - Laos'),
    ('LSO', 'LSO - Lesoto'),
    ('LVA', 'LVA - Letonia'),
    ('LBN', 'LBN - Líbano'),
    ('LBR', 'LBR - Liberia'),
    ('LBY', 'LBY - Libia'),
    ('LIE', 'LIE - Liechtenstein'),
    ('LTU', 'LTU - Lituania'),
    ('LUX', 'LUX - Luxemburgo'),
    ('MKD', 'MKD - Macedonia del Norte'),
    ('MDG', 'MDG - Madagascar'),
    ('MYS', 'MYS - Malasia'),
    ('MWI', 'MWI - Malaui'),
    ('MDV', 'MDV - Maldivas'),
    ('MLI', 'MLI - Malí'),
    ('MLT', 'MLT - Malta'),
    ('MAR', 'MAR - Marruecos'),
    ('MUS', 'MUS - Mauricio'),
    ('MRT', 'MRT - Mauritania'),
    ('MEX', 'MEX - México'),
    ('FSM', 'FSM - Micronesia'),
    ('MDA', 'MDA - Moldavia'),
    ('MCO', 'MCO - Mónaco'),
    ('MNG', 'MNG - Mongolia'),
    ('MNE', 'MNE - Montenegro'),
    ('MOZ', 'MOZ - Mozambique'),
    ('NAM', 'NAM - Namibia'),
    ('NRU', 'NRU - Nauru'),
    ('NPL', 'NPL - Nepal'),
    ('NIC', 'NIC - Nicaragua'),
    ('NER', 'NER - Níger'),
    ('NGA', 'NGA - Nigeria'),
    ('NOR', 'NOR - Noruega'),
    ('NZL', 'NZL - Nueva Zelanda'),
    ('OMN', 'OMN - Omán'),
    ('NLD', 'NLD - Países Bajos'),
    ('PAK', 'PAK - Pakistán'),
    ('PLW', 'PLW - Palaos'),
    ('PAN', 'PAN - Panamá'),
    ('PNG', 'PNG - Papúa Nueva Guinea'),
    ('PRY', 'PRY - Paraguay'),
    ('PER', 'PER - Perú'),
    ('POL', 'POL - Polonia'),
    ('PRT', 'PRT - Portugal'),
    ('GBR', 'GBR - Reino Unido'),
    ('CAF', 'CAF - República Centroafricana'),
    ('CZE', 'CZE - República Checa'),
    ('COG', 'COG - República del Congo'),
    ('COD', 'COD - República Democrática del Congo'),
    ('DOM', 'DOM - República Dominicana'),
    ('RWA', 'RWA - Ruanda'),
    ('ROU', 'ROU - Rumania'),
    ('RUS', 'RUS - Rusia'),
    ('WSM', 'WSM - Samoa'),
    ('KNA', 'KNA - San Cristóbal y Nieves'),
    ('SMR', 'SMR - San Marino'),
    ('VCT', 'VCT - San Vicente y las Granadinas'),
    ('LCA', 'LCA - Santa Lucía'),
    ('STP', 'STP - Santo Tomé y Príncipe'),
    ('SEN', 'SEN - Senegal'),
    ('SRB', 'SRB - Serbia'),
    ('SYC', 'SYC - Seychelles'),
    ('SLE', 'SLE - Sierra Leona'),
    ('SGP', 'SGP - Singapur'),
    ('SYR', 'SYR - Siria'),
    ('SOM', 'SOM - Somalia'),
    ('LKA', 'LKA - Sri Lanka'),
    ('SWZ', 'SWZ - Suazilandia'),
    ('ZAF', 'ZAF - Sudáfrica'),
    ('SDN', 'SDN - Sudán'),
    ('SSD', 'SSD - Sudán del Sur'),
    ('SWE', 'SWE - Suecia'),
    ('CHE', 'CHE - Suiza'),
    ('SUR', 'SUR - Surinam'),
    ('THA', 'THA - Tailandia'),
    ('TWN', 'TWN - Taiwán'),
    ('TZA', 'TZA - Tanzania'),
    ('TJK', 'TJK - Tayikistán'),
    ('TLS', 'TLS - Timor Oriental'),
    ('TGO', 'TGO - Togo'),
    ('TON', 'TON - Tonga'),
    ('TTO', 'TTO - Trinidad y Tobago'),
    ('TUN', 'TUN - Túnez'),
    ('TKM', 'TKM - Turkmenistán'),
    ('TUR', 'TUR - Turquía'),
    ('TUV', 'TUV - Tuvalu'),
    ('UKR', 'UKR - Ucrania'),
    ('UGA', 'UGA - Uganda'),
    ('URY', 'URY - Uruguay'),
    ('UZB', 'UZB - Uzbekistán'),
    ('VUT', 'VUT - Vanuatu'),
    ('VEN', 'VEN - Venezuela'),
    ('VNM', 'VNM - Vietnam'),
    ('YEM', 'YEM - Yemen'),
    ('DJI', 'DJI - Yibuti'),
    ('ZMB', 'ZMB - Zambia'),
    ('ZWE', 'ZWE - Zimbabue'),
]
