"""
Colombian departments (departamentos) for the region field.
"""

COLOMBIA_DEPARTMENTS = [
    ('amazonas', 'Amazonas'),
    ('antioquia', 'Antioquia'),
    ('arauca', 'Arauca'),
    ('atlantico', 'Atlántico'),
    ('bogota', 'Bogotá, D.C.'),
    ('bolivar', 'Bolívar'),
    ('boyaca', 'Boyacá'),
    ('caldas', 'Caldas'),
    ('caqueta', 'Caquetá'),
    ('casanare', 'Casanare'),
    ('cauca', 'Cauca'),
    ('cesar', 'Cesar'),
    ('choco', 'Chocó'),
    ('cordoba', 'Córdoba'),
    ('cundinamarca', 'Cundinamarca'),
    ('guainia', 'Guainía'),
    ('guaviare', 'Guaviare'),
    ('huila', 'Huila'),
    ('guajira', 'La Guajira'),
    ('magdalena', 'Magdalena'),
    ('meta', 'Meta'),
    ('narino', 'Nariño'),
    ('norte_santander', 'Norte de Santander'),
    ('putumayo', 'Putumayo'),
    ('quindio', 'Quindío'),
    ('risaralda', 'Risaralda'),
    ('san_andres', 'San Andrés y Providencia'),
    ('santander', 'Santander'),
    ('sucre', 'Sucre'),
    ('tolima', 'Tolima'),
    ('valle', 'Valle del Cauca'),
    ('vaupes', 'Vaupés'),
    ('vichada', 'Vichada'),
]
