#!/usr/bin/env bash
# deploy.sh — Split the volume manifest by fond and deploy scripts to all 5 droplets
#
# Prerequisites:
#   - doctl installed and authenticated (doctl auth init / doctl account get)
#   - All 5 zasqua-* droplets are SSH-accessible (run provision.sh + configure.sh first)
#   - volumes.csv is present in the same directory as this script (generated by Phase 1)
#
# Usage:
#   Run from the repo root or from the scripts/iiif/ directory — the script resolves
#   paths relative to its own location.
#
#     bash scripts/iiif/deploy.sh
#
# What it does:
#   1. Splits volumes.csv into one per-fond slice per droplet (keeps header row)
#   2. For each fond, looks up the droplet's public IP via doctl
#   3. SCPs the entire scripts/iiif/ directory to /root/zasqua/scripts/ on the droplet
#      (creating /root/zasqua/scripts/iiif/ as the working directory for the tiling scripts)
#   4. SCPs the per-fond manifest slice to /root/zasqua/volumes-{fond}.csv
#   5. Verifies the main ingest script and the manifest slice are present
#   6. Prints DEPLOYED: zasqua-{fond} at IP on success
#
# Idempotent: scp overwrites are safe; awk always regenerates slices from volumes.csv.
# Target layout on each droplet:
#   /root/zasqua/
#     scripts/iiif/
#       ingest_dropbox_volumes.py
#       iiif_tiling.py
#       volumes-{fond}.csv   <- only the slice for this droplet's fond

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
VOLUMES_CSV="$SCRIPT_DIR/volumes.csv"

if [[ ! -f "$VOLUMES_CSV" ]]; then
  echo "ERROR: volumes.csv not found at $SCRIPT_DIR/volumes.csv" >&2
  echo "       Run generate_volume_manifest.py (Phase 1) to produce it first." >&2
  exit 1
fi

# ── Fond-to-droplet mapping ───────────────────────────────────────────────────
# Keys are the droplet slug (and fond suffix); values are the fond column values
# as they appear in volumes.csv column 1.

declare -A DROPLETS=(
  [aht]=zasqua-aht
  [cabildos]=zasqua-cabildos
  [n1]=zasqua-n1
  [n2]=zasqua-n2
  [nvl]=zasqua-nvl
)

# Map from slug to the exact fond string used in volumes.csv column 1
declare -A FOND_VALUES=(
  [aht]=AHRB_AHT
  [cabildos]=AHRB_Cabildos
  [n1]=AHRB_N1
  [n2]=AHRB_N2
  [nvl]=AHRB_NVL
)

# ── Step 1: Split volumes.csv into per-fond slices ────────────────────────────

echo "Splitting volumes.csv into per-fond slices..."

for SLUG in aht cabildos n1 n2 nvl; do
  FOND_VAL="${FOND_VALUES[$SLUG]}"
  SLICE="$SCRIPT_DIR/volumes-${SLUG}.csv"

  awk -F',' -v fond="$FOND_VAL" 'NR==1 || $1==fond' "$VOLUMES_CSV" > "$SLICE"

  ROW_COUNT=$(( $(wc -l < "$SLICE") - 1 ))
  echo "  volumes-${SLUG}.csv: $ROW_COUNT rows (fond=$FOND_VAL)"
done

echo ""

# ── Steps 2–8: Deploy to each droplet ────────────────────────────────────────

for SLUG in aht cabildos n1 n2 nvl; do
  DROPLET_NAME="${DROPLETS[$SLUG]}"
  SLICE="$SCRIPT_DIR/volumes-${SLUG}.csv"

  echo "── Deploying to $DROPLET_NAME ──"

  # Step 2: Resolve droplet IP via doctl
  IP=$(doctl compute droplet get "$DROPLET_NAME" --format PublicIPv4 --no-header 2>/dev/null || true)
  if [[ -z "$IP" || "$IP" == "0.0.0.0" ]]; then
    echo "ERROR: Could not resolve IP for $DROPLET_NAME. Is the droplet running?" >&2
    exit 1
  fi
  echo "  IP: $IP"

  SCP_OPTS="-o StrictHostKeyChecking=no"
  SSH_OPTS="-o StrictHostKeyChecking=no -o BatchMode=yes"

  # Ensure target directory structure exists on the remote
  # shellcheck disable=SC2029
  ssh $SSH_OPTS "root@$IP" "mkdir -p /root/zasqua/scripts"

  # Step 3: SCP the entire scripts/iiif/ directory to /root/zasqua/scripts/ on the droplet
  # Copying $SCRIPT_DIR (the iiif/ dir itself) into /root/zasqua/scripts/ produces
  # /root/zasqua/scripts/iiif/ — matching the expected layout.
  echo "  Copying scripts/iiif/ -> root@$IP:/root/zasqua/scripts/ ..."
  scp $SCP_OPTS -r "$SCRIPT_DIR" "root@$IP:/root/zasqua/scripts/"

  # Step 4: SCP the per-fond manifest slice to /root/zasqua/volumes-{slug}.csv
  echo "  Copying volumes-${SLUG}.csv -> root@$IP:/root/zasqua/volumes-${SLUG}.csv ..."
  scp $SCP_OPTS "$SLICE" "root@$IP:/root/zasqua/volumes-${SLUG}.csv"

  # Step 5: Verify the ingest script is present — fail if missing
  REMOTE_SCRIPT="/root/zasqua/scripts/iiif/ingest_dropbox_volumes.py"
  if ! ssh $SSH_OPTS "root@$IP" "test -f $REMOTE_SCRIPT" 2>/dev/null; then
    echo "ERROR: ingest_dropbox_volumes.py not found at $REMOTE_SCRIPT on $DROPLET_NAME ($IP)" >&2
    exit 1
  fi
  echo "  Verified: $REMOTE_SCRIPT"

  # Step 6: Verify the manifest slice is present and print its line count
  REMOTE_SLICE="/root/zasqua/volumes-${SLUG}.csv"
  WC_OUTPUT=$(ssh $SSH_OPTS "root@$IP" "wc -l $REMOTE_SLICE" 2>/dev/null || true)
  if [[ -z "$WC_OUTPUT" ]]; then
    echo "ERROR: Could not read $REMOTE_SLICE on $DROPLET_NAME ($IP)" >&2
    exit 1
  fi
  echo "  Remote slice: $WC_OUTPUT"

  echo "DEPLOYED: $DROPLET_NAME at $IP"
  echo ""
done

echo "All 5 droplets deployed. Ready to tile."
