# Generated by Django 6.0 on 2025-12-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='extent',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
