# Generated by Django 6.0 on 2025-12-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_entity_honorific_function_neogranadina'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='given_name',
            field=models.CharField(blank=True, help_text='Given name(s), including particles (e.g., "Agustina del")', max_length=200),
        ),
        migrations.AddField(
            model_name='entity',
            name='surname',
            field=models.CharField(blank=True, db_index=True, help_text='Family name (without particles like de/del)', max_length=200),
        ),
    ]
