# Generated by Django 6.0 on 2026-02-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_ocr_text_to_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='short_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
